# Build documentation with MkDocs
#mkdocs:
#  configuration: mkdocs.yml
mkdocs:
  configuration: mkdocs.yml
  fail_on_warning: false

# Optionally build your docs in additional formats such as PDF and ePub
formats: all