# Build documentation with MkDocs
#mkdocs:
#  configuration: mkdocs.yml
# Required
version: 2

mkdocs:
  configuration: mkdocs.yml

# Optionally set the version of Python and requirements required to build your docs
python:
   version: 3.7
   install:
   - requirements: docs/requirements.txt