
language: python
python:
  - "3.7"
before_install:
  - pip install codecov
  - pip install python-coveralls

install:
  - pip install -r requirements.txt
  - pip uninstall TSErrors -y
  - python -m pip install git+https://github.com/AtrCheema/TSErrors.git
  - pip install keras-tcn

script:
  - python tests/test_activations.py
  - python tests/test_models.py
  - python tests/test_without_eager.py

after_success:
  - codecov # submit coverage
  - coveralls