
language: python
python:
  - "3.7"
before_install:
  - pip install codecov
  - pip install python-coveralls

install:
  - pip install -r requirements.txt
  - pip uninstall TSErrors -y
  - python -m pip install git+https://github.com/AtrCheema/TSErrors.git
  - pip install keras-tcn
  - pip install coverage

script:
  - coverage run -m unittest tests.test_activations
  - coverage run -m unittest tests.test_models
  - coverage run -m unittest tests.test_without_eager
  - coverage run -m unittest tests.test_utils

after_success:
  - codecov # submit coverage
  - coveralls
  - bash <(curl -s https://codecov.io/bash)