site_name: AI4Water

#google_analytics: ['UA-27795084-5']

repo_url: https://github.com/AtrCheema/AI4Water/tree/master

theme:
  name: "material"
  favicon: images/favicon.png
  logo: images/favicon.png

plugins:
- search
- autorefs
- mkdocstrings

pages:
- models: 'modelbuilding.md'
- Experiments: 'experiments.md'
- Hyperparameter optimization: 'hpo.md'
- preprocessing: 'preprocessing.md'
- postprocessing: 'postprocessing.md'
- Exploratory data analysis: 'eda.md'
- Evapotranspiration: 'evapotranspiration.md'
- Datasets: 'datasets.md'
- utils: 'utils.md'
