site_name: AI4Water

#google_analytics: ['UA-27795084-5']

repo_url: https://github.com/AtrCheema/AI4Water/tree/master

theme:
  name: "material"
  favicon: images/favicon.png
  logo: images/favicon.png

plugins:
- search
- autorefs
- mkdocstrings

pages:
- Model: 'modelbuilding.md'
- Performance metrics: 'metrics.md'
- hyperparameter optimization: 'hpo.md'
- Evapotranspiration: 'evapotranspiration.md'
- datasets: 'datasets.md'
- experiments: 'experiments.md'
- utils: 'utils.md'
