name: tf230
on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements_all.txt; fi
    - name: Test with unittest
      run: |
        conda install pytest
        pip install coverage
        pip install codecov
        pip install python-coveralls

        coverage run -m unittest tests.test_model_class
        coverage run -m unittest tests.test_utils
        coverage run -m unittest tests.test_models